Closing Requests stream on EndOfStream method
techmo-pl/sarmata-client pull request #1
Opened 2016-11-21 12:06 UTC by tomjad

2016-11-21 12:15 UTC, skurzok requested changes

2016-11-21 12:15 UTC, skurzok commented on cpp/libsarmata-client/RemoteSession.cpp
> +	samplesStreamCompleted = false;
please move to ctor initialization list

2016-11-21 12:15 UTC, skurzok commented on cpp/libsarmata-client/RemoteSession.h
> +		bool samplesStreamCompleted;
add trailing underscore _ to name

2016-11-21 12:20 UTC, tomjad commented on cpp/libsarmata-client/RemoteSession.cpp
> +	samplesStreamCompleted = false;
When we moved initialization to the ctor, we assume that Open() could be called just once. And this is not asserted here. Is it correct assumption?

2016-11-22 08:41 UTC, skurzok commented on cpp/libsarmata-client/RemoteSession.cpp
> +	samplesStreamCompleted = false;
You're right, we should leave it here, but add it also to ctor to prevent dtor to close stream basing on potentially randomly initialized variable.

2016-11-22 09:39 UTC, merged